### ISSUE TITLE
not working with some videos

### ISSUE THREAD

**Issue by Hardik-G1** [xTEddie/McHacks2017#4]
```
[2020-07-18 11:57:13,373] ERROR in app: Exception on /search_keyword [POST]
Traceback (most recent call last):
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ronni\OneDrive\Desktop\McHacks2017\app.py", line 22, in searchKeyWord
    result = search_keywords(url, keyword)
  File "C:\Users\ronni\OneDrive\Desktop\McHacks2017\youtube_transcriber.py", line 69, in search_keywords
    status_code, content = transcribe_video(youtube_url)
  File "C:\Users\ronni\OneDrive\Desktop\McHacks2017\youtube_transcriber.py", line 46, in transcribe_video
    url = get_transcribe_url("https://www.youtube.com/watch?v={}".format(id))
  File "C:\Users\ronni\OneDrive\Desktop\McHacks2017\youtube_ghost.py", line 23, in get_transcribe_url
    driver.execute_script(JS_SCRIPT)
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ronni\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'length' of undefined
  (Session info: chrome=84.0.4147.89)

```

**Comment by SudhanshuBlaze** [comment]
Hiii @Hardik-G1 I am also getting the same error on MAC, can you please tell me the soltution

**Comment by SudhanshuBlaze** [comment]
How do you solve this issue? It's still not fixed, why do you close this issue? 

[OPEN ISSUE](https://github.com/xTEddie/McHacks2017/issues/5)

**Comment by SudhanshuBlaze** [comment]
Guys please help @xTEddie @Soqueen @SweetmanTech @shubhamurthy.
I am in desperate need.
